create table content
(
    id   bigint  not null generated by default as identity,
    type varchar not null,
    url  varchar,
    primary key (id)
);

create table usr
(
    id        bigint not null generated by default as identity,
    cookie    varchar(36),
    game_type varchar default 'NOT_WATCHED',
    primary key (id)
);

create table user_content
(
    user_id    bigint references usr (id),
    content_id bigint references content (id),
    primary key (user_id, content_id),
    is_liked   bool,
    is_watched bool default false
);

alter table content
    add constraint unique_url unique (url);
alter table usr
    add constraint unique_cookie unique (cookie);